services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${P_DB}
      - POSTGRES_USER=${P_USER}
      - POSTGRES_PASSWORD=${P_PASS}
    ports:
      - "5432:5432"
    volumes:
      - marketplace-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: "pg_isready -U ${P_USER}"
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build:
      context: app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${P_DB}
      - POSTGRES_USER=${P_USER}
      - POSTGRES_PASSWORD=${P_PASS}
    depends_on:
      db:
        condition: service_healthy
volumes:
  marketplace-data:
    external: true